### ISSUE TITLE
things that should be cherry-picked to 1.4

### ISSUE THREAD

**Issue by jgrewe** [G-Node/nix#749]
- [x] fix of hdf update #744 
- [x] data slicing method #736 
- [x] retrieve multiple slices in one go #722 
- [x] DataView and Filter changes #740 
- [x] default appendDimension arguments #727 

something else?

**Comment by gicmo** [comment]
What about the ForceOpen open flag?
